# Generated by Django 2.0.3 on 2018-03-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('siret', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='Siret')),
                ('raisonSocial', models.CharField(max_length=50, verbose_name='Raison Sociale')),
                ('adresse', models.CharField(max_length=50)),
                ('codePostal', models.CharField(max_length=5)),
                ('ville', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=12)),
            ],
        ),
    ]
