# Generated by Django 2.0.3 on 2018-03-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irontask_app', '0002_auto_20180312_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('ageMin', models.PositiveSmallIntegerField()),
                ('ageMax', models.PositiveSmallIntegerField()),
                ('sexe', models.BooleanField(choices=[('F', 'Feminin'), ('M', 'Masculin')])),
            ],
        ),
        migrations.CreateModel(
            name='Intervenant',
            fields=[
                ('siret', models.PositiveIntegerField(max_length=14, primary_key=True, serialize=False)),
                ('raisonSocial', models.CharField(max_length=50, verbose_name='Raison Sociale')),
                ('type', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=200)),
                ('codePostal', models.PositiveSmallIntegerField(max_length=5)),
                ('ville', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('qteTotal', models.PositiveIntegerField()),
                ('lieuStockage', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='siret',
            field=models.PositiveIntegerField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
