# Generated by Django 2.0.3 on 2018-03-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irontask_app', '0002_auto_20180322_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='sexe',
            field=models.CharField(choices=[('F', 'Feminin'), ('M', 'Masculin')], max_length=1),
        ),
    ]
