# Generated by Django 2.0.2 on 2018-03-30 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irontask_app', '0003_auto_20180322_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='telephonePort',
            new_name='telephonePortable',
        ),
    ]
