# Generated by Django 2.0.2 on 2018-03-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irontask_app', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triathlon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('heureDepart', models.TimeField(verbose_name='heureDepart')),
                ('codePostal', models.CharField(max_length=5, verbose_name='codePostal')),
                ('adresse', models.CharField(max_length=50, verbose_name='adresse')),
                ('ville', models.CharField(max_length=50, verbose_name='ville')),
            ],
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='siret',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
