# Generated by Django 2.0.2 on 2018-03-19 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irontask_app', '0005_auto_20180317_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateFin', models.DateField(verbose_name='DateFin')),
                ('NiveauAvancement', models.CharField(choices=[('0', 'Aucune'), ('1', 'Faible'), ('2', 'Moyen'), ('3', 'Important')], max_length=1)),
                ('Triathlon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='irontask_app.Triathlon')),
            ],
        ),
        migrations.AlterField(
            model_name='intervenant',
            name='codePostal',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='intervenant',
            name='siret',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
